// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTywvI4kHfdhyhKx74ymFJJwVKE2WeNi8',
    appId: '1:200095662369:android:8e8603347c8bbb65447e60',
    messagingSenderId: '200095662369',
    projectId: 'fir-db5ef',
    storageBucket: 'fir-db5ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAufBjTFuyhTFYxLqW8XCXzXPCJkLWZqCs',
    appId: '1:200095662369:ios:5dc823e2ee2a8636447e60',
    messagingSenderId: '200095662369',
    projectId: 'fir-db5ef',
    storageBucket: 'fir-db5ef.firebasestorage.app',
    androidClientId: '200095662369-q2qmu0oe2u8jaca5l3jrp9uh5leifg5d.apps.googleusercontent.com',
    iosClientId: '200095662369-am1revc5khss9rcpj79q21leu4h1mpfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.wellbyn',
  );
}
